// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnicaLlamada.Infrastructure.Persistence;

#nullable disable

namespace PruebaTecnicaLlamada.Infrastructure.Migrations
{
    [DbContext(typeof(PruebaTecnicaLlamadaDbContext))]
    [Migration("20251117174135_Intentos")]
    partial class Intentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaTecnicaLlamada.Domain.AggregateModel.AggregateDeportista.Deportista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Deportistas");
                });

            modelBuilder.Entity("PruebaTecnicaLlamada.Domain.AggregateModel.AggregateDeportista.Intentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Arranque")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeportistaId")
                        .HasColumnType("int");

                    b.Property<int>("Envion")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeportistaId");

                    b.ToTable("Intentos");
                });

            modelBuilder.Entity("PruebaTecnicaLlamada.Domain.AggregateModel.AggregateDeportista.Intentos", b =>
                {
                    b.HasOne("PruebaTecnicaLlamada.Domain.AggregateModel.AggregateDeportista.Deportista", "Deportista")
                        .WithMany("Intentos")
                        .HasForeignKey("DeportistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deportista");
                });

            modelBuilder.Entity("PruebaTecnicaLlamada.Domain.AggregateModel.AggregateDeportista.Deportista", b =>
                {
                    b.Navigation("Intentos");
                });
#pragma warning restore 612, 618
        }
    }
}
